# Generated by Anaconda 38.23.4
# Generated by pykickstart v3.47
#version=F38
# Use graphical install
graphical

# Keyboard layouts
keyboard --vckeymap=pl --xlayouts='pl'
# System language
lang pl_PL.UTF-8


url --mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=fedora-38&arch=x86_64
repo --name=update --mirrorlist=http://mirrors.fedoraproject.org/mirrorlist?repo=updates-released-f38&arch=x86_64

%packages
@^server-product-environment
docker
%end

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.7.1
ignoredisk --only-use=nvme0n1
autopart
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone Europe/Warsaw --utc

# Root password
rootpw --iscrypted $y$j9T$TIShGjBG7wIvrDapDgsfooK4$z4zo./ea/dccEGzRSSRDTBC.zM9hZiEQeduIUXiy189
user --groups=wheel --name=pawel --password=$y$j9T$f.M/RFzz5a92KzDSrgPBQT8E$W2fTPpZf2UuP6V0veql5lENIuTzYGK/I2SbyXZ7kLg1 --iscrypted --gecos="pawel"


%post --log=/var/log/post.log

systemctl enable docker
systemctl start docker

#!/bin/bash
systemctl start docker
docker pull oleniakstudia/express_deploy:latest
docker run -d -p 8000:8000 oleniakstudia/express_deploy:latest
EOF
